# Generated by Django 5.0.3 on 2024-03-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repository',
            new_name='repositories',
        ),
        migrations.RenameModel(
            old_name='DependenciesMap',
            new_name='repository_dependency_map',
        ),
        migrations.RenameModel(
            old_name='InformationMap',
            new_name='repository_info_map',
        ),
    ]
